### ISSUE TITLE
Request for `aws_cloudfront_origin_access_control` resource

### ISSUE THREAD

**Issue by jeanduplessis** [upbound/provider-aws#100]
### What resource do you need?
Terraform Resource Name: `aws_cloudfront_origin_access_control`
[Terraform link.](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_origin_access_control)

Relates to private issue: https://github.com/upbound/official-providers/issues/825

**Comment by sergenyalcin** [comment]
I tried to generate this resource. However, this resource is not available in our provider version: `4.15.1`

It is available after the `4.29.0` version. So we need to upgrade our provider version to generate this resource. I will suggest upgrading to the `latest` version of provider-aws.

**Comment by dverveiko** [comment]
Resource successfully tested. I close this ticket as done.
