### ISSUE TITLE
WebIdentity credential source relies on eks.amazonaws.com/role-arn ServiceAccount annotation

### ISSUE THREAD

**Issue by nresare** [upbound/provider-aws#1007]
### What happened?
Experimenting with having a single provider-aws-s3 assume different AWS IAM roles from different ProviderConfig objects, I noticed that using the WebIdentity credential source somewhat unintuitively depends on having the ServiceAccount referenced in the provider Deployment having the `eks.amazonaws.com/role-arn` annotation.

My understanding is that the reason for this is the following: when a Pod is being created that references a service account with the `eks.amazonaws.com/role-arn` annotation, some EKS internal mutating admission controller will modify the Pod object in the following way:

1.  add a projected volume with a serviceAccountToken block with an audience set to `sts.amazonaws.com`
2.  add a mount point in all containers referencing the volume in 1.
3.  set the `AWS_WEB_IDENTITY_TOKEN_FILE` environment variable to the token file in on the mount from 2.

If the annotation on the ServiceAccount is not found, the provider-aws-s3 will attempt to open the token file empty string (since looking up a nonexistent environment variable will not fail but return an empty string), normalized to `.`, which fails with the error message attached at the bottom of this report.

### How can we reproduce it?
By creating an provider-aws-s3 provider and a default ProviderConfig using a WebIdentity credential source, without any DeploymentRuntimeConfig containing a serviceAccountTemplate to add the `eks.amazonaws.com/role-arn` annotation and create an entity controlled by the provider (I tried with an S3 Object) referencing the mentioned ProviderConfig.

Inspecting the Pod object that the provider creates, it should be clear that the `AWS_WEB_IDENTITY_TOKEN_FILE` is not set, and attempting to act on the entity will cause the CannotConnectToProvider event detailed below to be emitted.

### Suggested fixes

The proper fix to my mind would be to modify the Deployment spec for all providers to include a service account token projection as this is a [publicly available feature](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/) of all supported versions of Kubernetes and modify the provider code to use this token.

As a temporary stop gap measure the docs could be updated to detail that the ServiceAccount annotation hack is currently needed.

### What environment did it happen in?

* Crossplane Version: v1.14.3
* Provider Version: v0.45.0
* Kubernetes Version: v1.27.7-eks-4f4795d
* Kubernetes Distribution: EKS

The specific CannotConnectToProvider event associated with an s3 Object triggering this error:

```  Warning  CannotConnectToProvider  0s (x5 over 13s)  managed/s3.aws.upbound.io/v1beta1, kind=object  cannot initialize the no-fork async external client: cannot get terraform setup: cannot get account id: failed to retrieve aws credentials from aws config: failed to refresh cached credentials, failed to retrieve jwt from provide source, unable to read file at .: read .: is a directory```

**Comment by maganuk** [comment]
@nresare do you have a work around for this? I just cant get the webidentity to work. I tried putting in a dummy rolearn in the ControllerConfig along with roleARN in the ProviderConfig but that doesn't work. I want multiple ProviderConfigs, each targeting a different role. I dont want to have multiple Providers with multiple ControllerConfigs. How can I get this to work? IRSA on its own works fine.

**Comment by billabongrob** [comment]
This is impacting my team as well.  I haven't been able to leverage the WebIdentity properly - according to the documentation.  Is leveraging the IRSA documentation better at this point, since the webidentity doesn't work as described on the tin?

**Comment by sethfduke** [comment]
I have run into this issue as well. Web Identity previously worked without issue. At some point during upgrades, it quit working with the same errors mentioned here.

**Comment by turkenf** [comment]
Hello folks,

Thank you for bringing up this issue, we were able to reproduce the issue with @erhancagirici. We also need to update the [documentation](https://github.com/upbound/provider-aws/blob/main/AUTHENTICATION.md#web-identity) regarding the Web Identity authentication method.
