### ISSUE TITLE
Request for `aws_launch_configuration` resource

### ISSUE THREAD

**Issue by jeanduplessis** [upbound/provider-aws#101]
### What resource do you need?

Terraform Resource Name: `aws_launch_configuration`
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_configuration

Relates to private issue: https://github.com/upbound/official-providers/issues/826

**Comment by turkenf** [comment]
https://marketplace.upbound.io/providers/upbound/provider-aws/v0.18.0/resources/autoscaling.aws.upbound.io/LaunchConfiguration/v1beta1

**Comment by jeanduplessis** [comment]
Thanks, @turkenf for confirming this is already in place. I will close this issue.
