### ISSUE TITLE
Imported RDS can't be changed 

### ISSUE THREAD

**Issue by sterziev88** [upbound/provider-aws#1076]
### What happened?
I imported successful a RDS from old crossplane provider version 0.32 to upbound/provider-aws-rds:v0.46.0.
But after that when I try to change some parameter I see this error in argocd logs:

     message: >-
        async update failed: failed to update the resource: [{0 updating RDS DB
        Instance (test): operation error RDS:
        ModifyDBInstance, https response error StatusCode: 403, RequestID:
        1db6437f-54e5-48dd-a268-689807514d69, api error ExpiredToken: The
        security token included in the request is expired  []}]

### What environment did it happen in?

* Crossplane Version: 1.14.2
* Provider Version: 0.46.0
* Kubernetes Version: 1.27

**Comment by turkenf** [comment]
@sterziev88 the error message says that the security token you are using has expired, have you checked?

**Comment by sterziev88** [comment]
Hi @turkenf, yes I see that but I don't know which one is that token and where I have to check it.. According to me that change should be implemented by the role which I use related to my provider-config.. I use crossplane for many resources and see this error for first time :D

**Comment by turkenf** [comment]
Yes, I see, but this issue does not seem to be related to the version of the provider. To be sure, can you try the same process by upgrading the provider version to 43.0?
If it is not repeated in v0.43.0, could you please update the description of the issue by adding the steps to reproduce and relevant example MRs?

**Comment by turkenf** [comment]
If the issue occurs in version 0.43.0, as I said, it does not seem to be caused by the version. Could you please check if you can change the same parameter in version 0.32.0? You can also check if the credentials used have the correct permissions.

**Comment by sterziev88** [comment]
I changed the same parameter with version 0.32 and it works. Then I create another resource with version 0.46 in the same cluster and account to check the permission and that works as well... So the issue with the token still exist only when I try to change a parameter with the new provider

**Comment by sterziev88** [comment]
I recreated the RDS bases with the new provider version

**Comment by alekseikurepin** [comment]
Looks similar:
`│ Deprecated Source:                                                                                                                                                                                                                                                         │
│   Component:  managed/sqs.aws.upbound.io/v1beta1, kind=queue                                                                                                                                                                                                               │
│ Event Time:   <nil>                                                                                                                                                                                                                                                        │
│ Kind:         Event                                                                                                                                                                                                                                                        │
│ Metadata:                                                                                                                                                                                                                                                                  │
│   Creation Timestamp:  2025-05-13T09:15:27Z                                                                                                                                                                                                                                │
│   Resource Version:    1051301251                                                                                                                                                                                                                                          │
│   UID:                 6a63ce5e-d2fc-4a95-a548-9480a86504e3                                                                                                                                                                                                                │
│ Note:                  async update failed: failed to update the resource: [{0 waiting for SQS Queue (https://sqs.eu-west-3.amazonaws.com/{aws-id}/alarm-events) attributes update: timeout while waiting for state to become 'equal' (last state: 'notequal', timeout │
│ : 2m0s)  []}]                                                                                                                                                                                                                                                              │
│ Reason:                CannotUpdateExternalResource                                                                                                                                                                                                                        │
│ Regarding:                                                                                                                                                                                                                                                                 │
│   API Version:         sqs.aws.upbound.io/v1beta1                                                                                                                                                                                                                          │
│   Kind:                Queue                                                                                                                                                                                                                                               │
│   Name:                alarm-events                                                                                                                                                                                                                                        │
│   Resource Version:    1051301249                                                                                                                                                                                                                                          │
│   UID:                 03849b79-2b89-4c68-956f-e7606e00cd0b                                                                                                                                                                                                                │
│ Reporting Controller:  managed/sqs.aws.upbound.io/v1beta1, kind=queue`
