### ISSUE TITLE
Request for `opensearch_monitor` resource

### ISSUE THREAD

**Issue by albertoCrego** [upbound/provider-aws#1172]
### What resource do you need?

Support Opensearch Provider
https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs

Terraform Resource Names:
- [opensearch_monitor](https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/monitor)
- [opensearch_anomaly_detection](https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/anomaly_detection)
- [opensearch_dashboard_tenant](https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/dashboard_tenant)
- [opensearch_dashboard_object](https://registry.terraform.io/providers/opensearch-project/opensearch/latest/docs/resources/dashboard_object)

### What is your use case?
Deploy monitoring logs resources and visualisations directly with the Crossplane Provider.

**Comment by blakeromano** [comment]
I don't believe this would fall into the scope of the `provider-aws` I believe you'd want to look at this provider https://github.com/dkb-bank/provider-opensearch

**Comment by jeanduplessis** [comment]
@blakeromano is correct, this provider is limited to the AWS resources only.

I'll close this issue for now.
