### ISSUE TITLE
Moving directconnect (5) resources to v1beta1 version

### ISSUE THREAD

**Issue by sergenyalcin** [upbound/provider-aws#12]
Moving 5 resources in the `directconnect` group:

- [x] [`aws_dx_connection`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_connection)
- [x] [`aws_dx_connection_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_connection_association)
- [x] [`aws_dx_gateway`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_gateway)
- [x] [`aws_dx_lag`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_lag)
- [x] [`aws_dx_public_virtual_interface`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_public_virtual_interface)

**Comment by svscheg** [comment]
Splited items: 
https://github.com/upbound/provider-aws/issues/224 - waiting merge https://github.com/upbound/provider-aws/pull/221
https://github.com/upbound/provider-aws/issues/216 - complex task, need second account
