### ISSUE TITLE
Upgrade underlying AWS terraform provider

### ISSUE THREAD

**Issue by jeanduplessis** [upbound/provider-aws#154]
### What problem are you facing?

The current Terraform provider is outdated.

### How could Official AWS Provider help solve your problem?
Upgrade to the latest Terraform provider for AWS to enable access to more resources and bug fixes

**Comment by ulucinar** [comment]
An initial PR for observation and incorporating tooling (such as breaking API changes reporting) is here:
https://github.com/upbound/provider-aws/pull/173

**Comment by ulucinar** [comment]
Turns out we have an issue with the `pull-docs` target. Will try to open PRs addressing it for the official providers and the upjet template repo:
- https://github.com/upbound/provider-aws/pull/176
