### ISSUE TITLE
A preview version which include all CRDs

### ISSUE THREAD

**Issue by milonjames** [upbound/provider-aws#166]
Hello,

Will there be a preview version release just like the provider-jet-aws which includes all CRDs ?

Ref: https://github.com/crossplane-contrib/provider-jet-aws/releases/tag/v0.5.0-preview

Thanks

**Comment by turkenh** [comment]
Hello @milonjames,
Currently, we have no such plans. 
Feel free to open issues to specific resources you need or, even better, open a PR configuring the resources you need by following the [documentation](https://github.com/upbound/upjet/blob/main/docs/add-new-resource-short.md).
