### ISSUE TITLE
Request for AWS EventBridge resources

### ISSUE THREAD

**Issue by milonjames** [upbound/provider-aws#167]
It would be great to have support for AWS EventBridge resources.

Thanks!

**Comment by ulucinar** [comment]
When this issue is closed via a merged PR, we had better mark the corresponding resources as completed (remove them from the issue with a comment listing these resources) in https://github.com/upbound/provider-aws/issues/63:
```
aws_cloudwatch_event_api_destination
aws_cloudwatch_event_archive
aws_cloudwatch_event_bus
aws_cloudwatch_event_bus_policy
aws_cloudwatch_event_connection
aws_cloudwatch_event_permission
aws_cloudwatch_event_rule
aws_cloudwatch_event_target
```
