### ISSUE TITLE
Moving EC2(1) resource to v1beta1 version

### ISSUE THREAD

**Issue by dverveiko** [upbound/provider-aws#217]
Moving v1beta1 1 resource to the `ec2` group:
- [ ] [`aws_ami_from_instance`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami_from_instance) - Bug (https://github.com/upbound/provider-aws/issues/218)

**Comment by sergenyalcin** [comment]
Closing as duplicate #218
