### ISSUE TITLE
Configure grafana(1), gamelift(1)

### ISSUE THREAD

**Issue by sergenyalcin** [upbound/provider-aws#22]
External name configuration of 1 resource in the grafana group:

[aws_grafana_license_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/grafana_license_association)

External name configuration of 1 resource in the gamelift group:

[aws_gamelift_game_server_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/gamelift_game_server_group)

**Comment by ulucinar** [comment]
Corresponding issues:
https://github.com/upbound/provider-aws/issues/256
https://github.com/upbound/provider-aws/issues/257
