### ISSUE TITLE
Moving emrcontainers (1) resources to v1beta1 version

### ISSUE THREAD

**Issue by sergenyalcin** [upbound/provider-aws#295]
Moving1 resource in the emrcontainers group:

- [ ] [aws_emrcontainers_virtual_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emrcontainers_virtual_cluster)

**Comment by steperchuk** [comment]
Require https://github.com/upbound/provider-aws/issues/294

**Comment by dverveiko** [comment]
This issue was combined with #294
