### ISSUE TITLE
Moving EC2 (17) resources to v1beta1 version

### ISSUE THREAD

**Issue by muvaf** [upbound/provider-aws#30]
Moving v1beta1 17 resources to the `ec2` group:
- [x] [`aws_ami`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami)
- [x] [`aws_ami_copy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami_copy)
- [x] [`aws_ami_launch_permission`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami_launch_permission)
- [x] [`aws_customer_gateway`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/customer_gateway)
- [x] [`aws_default_network_acl`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_network_acl)
- [x] [`aws_default_route_table`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_route_table)
- [x] [`aws_vpc_ipam`](https://registry.terraform.io/providers/hashicorp/aws/4.15.1/docs/resources/vpc_ipam)
- [x] [`aws_vpc_ipam_pool`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_pool)
- [x] [`aws_vpc_ipam_scope`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_scope)
- [x] [`aws_vpc_ipam_pool_cidr`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_pool_cidr)
- [x] [`aws_vpc_ipam_pool_cidr_allocation`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_pool_cidr_allocation)
- [ ] [`aws_vpc_ipv6_cidr_block_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipv6_cidr_block_association)
- [x] [`aws_vpn_connection`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_connection)
- [x] [`aws_vpn_connection_route`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_connection_route)
- [x] [`aws_vpn_gateway`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_gateway)
- [x] [`aws_vpn_gateway_attachment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_gateway_attachment)
- [x] [`aws_vpn_gateway_route_propagation`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_gateway_route_propagation)

Extracted from https://github.com/upbound/official-providers/issues/252 and https://github.com/upbound/provider-aws/issues/64

**Comment by dverveiko** [comment]
[aws_vpc_ipam_pool_cidr](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_pool_cidr) is absent neither in `externalnamenottested.go` nor `externalname.go` (also checked `skipList` in  `provider.go`). 
This resource is required to test [aws_vpc_ipam_pool_cidr_allocation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_pool_cidr_allocation). 
So both resources are blocked.

**Comment by dverveiko** [comment]
[aws_vpc_ipv6_cidr_block_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipv6_cidr_block_association) also depend on [aws_vpc_ipam_pool_cidr](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_pool_cidr), so this resource is blocked too.

**Comment by dverveiko** [comment]
[aws_ami_from_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami_from_instance) - after creation AMI status of resource changing from READY=True / SYNCED=True to READY=True / SYNCED=False. Resource logs attached. 

[amifrominstance.log](https://github.com/upbound/provider-aws/files/10094047/amifrominstance.log)
