### ISSUE TITLE
Moving opsworks (17) resources to v1beta1 version

### ISSUE THREAD

**Issue by sergenyalcin** [upbound/provider-aws#313]
Moving 17 resources in the opsworks group:

- [x] [aws_opsworks_static_web_layer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_static_web_layer)
- [x] [aws_opsworks_user_profile](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_user_profile)
- [x] [aws_opsworks_application](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_application)
- [x] [aws_opsworks_custom_layer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_custom_layer)
- [x] [aws_opsworks_ecs_cluster_layer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_ecs_cluster_layer)
- [x] [aws_opsworks_ganglia_layer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_ganglia_layer)
- [x] [aws_opsworks_haproxy_layer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_haproxy_layer)
- [x] [aws_opsworks_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_instance)
- [x] [aws_opsworks_java_app_layer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_java_app_layer)
- [x] [aws_opsworks_memcached_layer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_memcached_layer)
- [x] [aws_opsworks_mysql_layer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_mysql_layer)
- [x] [aws_opsworks_nodejs_app_layer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_nodejs_app_layer)
- [x] [aws_opsworks_permission](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_permission)
- [x] [aws_opsworks_php_app_layer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_php_app_layer)
- [x] [aws_opsworks_rails_app_layer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_rails_app_layer)
- [x] [aws_opsworks_rds_db_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_rds_db_instance)
- [x] [aws_opsworks_stack](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_stack)

**Comment by kdibrov** [comment]
Stack is required for all opsworks resources, but it fails with this error:
message: 'observe failed: cannot run refresh: refresh failed: Missing required
      argument: The argument "region" is required, but no definition was found.'

**Comment by kdibrov** [comment]
As suggested by @sergenyalcin added the following to overrides.go:24:
```
if r.ShortGroup == "iam" || r.ShortGroup == "opsworks" {
   return
}
```
