### ISSUE TITLE
Configure sfn (2)

### ISSUE THREAD

**Issue by luebken** [upbound/provider-aws#32]
External name configuration of 2 resources in the `sfn` group:
* [`aws_sfn_activity`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sfn_activity)
* [`aws_sfn_state_machine`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sfn_state_machine)

Extracted from https://github.com/upbound/provider-aws/issues/55

**Comment by ulucinar** [comment]
Closing this issue as it looks like we have already configured these two resources:
https://github.com/upbound/provider-aws/blob/3bb79e63d4429fa1113ebda5ee28a413db86a7df/config/externalname.go#L987
