### ISSUE TITLE
Configure servicediscovery (1)

### ISSUE THREAD

**Issue by luebken** [upbound/provider-aws#33]
External name configuration of 2 resources in the `servicediscovery` group:
* [`aws_service_discovery_service`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/service_discovery_service)

Extracted from https://github.com/upbound/provider-aws/issues/55

**Comment by ulucinar** [comment]
Removing `aws_service_discovery_public_dns_namespace` from the list as we already have it configured here:
https://github.com/upbound/provider-aws/blob/3bb79e63d4429fa1113ebda5ee28a413db86a7df/config/externalname.go#L746

**Comment by ulucinar** [comment]
https://github.com/upbound/provider-aws/issues/251
