### ISSUE TITLE
Configure elasticache (3)

### ISSUE THREAD

**Issue by luebken** [upbound/provider-aws#34]
External name configuration of 3 resources in the `elasticache` group:
* [`aws_elasticache_global_replication_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_global_replication_group)
* [`aws_elasticache_security_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_security_group)
* [`aws_elasticache_user_group_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_user_group_association)

Extracted from https://github.com/upbound/provider-aws/issues/64

**Comment by ulucinar** [comment]
Corresponding issue: https://github.com/upbound/provider-aws/issues/252
