### ISSUE TITLE
Request for route53 `zone_association` resource

### ISSUE THREAD

**Issue by duizabojul** [upbound/provider-aws#393]
### What resource do you need?

Terraform Resource Name: [route53_zone_association](https://registry.terraform.io/providers/aaronfeng/aws/latest/docs/resources/route53_zone_association)

### What is your use case?

We need to associate a private hosted zone to multiple VPCs

**Comment by ytsarev** [comment]
@duizabojul thanks a lot for raising this issue. We carefully investigated the associated  APIs and came to the following conclusion https://github.com/upbound/provider-aws/pull/463#issuecomment-1413613595 .

To summarize it here, we will avoid adding potentially conflicting dedicated `route53_zone_association` and stick with inline `vpc` association array that was recently added to `Zone` resource in https://github.com/upbound/provider-aws/pull/456

I hope it helps!
