### ISSUE TITLE
rds: `Instance` kmsKeyIdRef wants ARN...

### ISSUE THREAD

**Issue by AaronME** [upbound/provider-aws#411]
### What happened?
Attempted to reference a crossplane created KMS Key using kmsKeyIdRef on Instance.rds.aws.upbound.io resource.

Received the error:

```
observe failed: cannot run refresh: refresh failed: "kms_key_id" (3cefab1e-802d-4567-9a0b-4d50ae26105a) is an invalid ARN: arn: invalid prefix
```

The kmsKeyIdRef is pulling the id of the key, but rds expects the ARN.

### How can we reproduce it?
Attempt to create an rds instance with kmsKeyIdRef.

### What environment did it happen in?

* Universal Crossplane Version: v1.10.1-up.1
* Provider Version: v0.25.0

**Comment by ulucinar** [comment]
Thank you @AaronME for reporting this issue. Opened PR #483 to fix the configuration and to test it.
