### ISSUE TITLE
Configure ram (4)

### ISSUE THREAD

**Issue by luebken** [upbound/provider-aws#42]
External name configuration of 4 resources in the `ram` group:
* [`aws_ram_principal_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ram_principal_association)
* [`aws_ram_resource_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ram_resource_association)
* [`aws_ram_resource_share`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ram_resource_share)
* [`aws_ram_resource_share_accepter`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ram_resource_share_accepter)

**Comment by ulucinar** [comment]
Corresponding issue: https://github.com/upbound/provider-aws/issues/253
