### ISSUE TITLE
Add support for `ManageMasterUserPassword` to RDS Instance

### ISSUE THREAD

**Issue by hasheddan** [upbound/provider-aws#423]
### What problem are you facing?

AWS recently added AWS Secrets Manager integration with RDS for managing passwords: https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-rds-integration-aws-secrets-manager/

### How could Official AWS Provider help solve your problem?

The RDS API now supports a [`ManageMasterUserPassword`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html#:~:text=Required%3A%20No-,ManageMasterUserPassword,-A%20value%20that) field that allows for deferring password management to AWS Secrets Manager. We should also add support for that field.

**Comment by hasheddan** [comment]
Issue tracking adding the same functionality to Terraform: https://github.com/hashicorp/terraform-provider-aws/issues/28538

**Comment by svscheg** [comment]
Need bump with latest terraform version 
Now we have attribute manage_master_user_password for the latest terraform version (4.62.0).

**Comment by turkenf** [comment]
I am closing this issue because this field is now available: https://github.com/upbound/provider-aws/blob/fb0fb486e6225cdab27a447c48cb36f98464884e/apis/rds/v1beta1/zz_instance_types.go#L832
