### ISSUE TITLE
Moving kafka (1) resources to v1beta1 version

### ISSUE THREAD

**Issue by luebken** [upbound/provider-aws#43]
External name configuration of 1 resource in the `kafka` group:
- [ ] [`aws_msk_scram_secret_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_scram_secret_association)

Extracted from https://github.com/upbound/provider-aws/issues/61

**Comment by chlunde** [comment]
It looks like kafka-cluster is already there, but I'd like to try to configure scram secrets in `upbound/provider-aws`.

**Comment by ulucinar** [comment]
Hi @chlunde,
Thank you for tackling with the `aws_msk_scram_secret_association` resource. As you mentioned, `aws_msk_configuration` and `aws_msk_cluster` are already configured, and hence I'm removing them from the description.
