### ISSUE TITLE
rds: WriteConnectionSecretToRef not working

### ISSUE THREAD

**Issue by josephferrero** [upbound/provider-aws#442]
### What happened?

I am creating a Postgres instance with the rds api. I have set:
`  writeConnectionSecretToRef:
    name: db-conn
    namespace: my-namespace`

For some reason the only data being written to the secret is `attribute.password`. The Postgres instance is creating successfully and has an endpoint.

I need the endpoint of the Postgres instance in the secret. This was working on the `database.aws.crossplane.io/v1beta1` api version.

I also tried using the `publishConnectionDetailsTo` spec field which failed to create any secret at all.

### How can we reproduce it?

If I delete the Postgres instance and recreate it the secret will be created, but only with the password data.

### What environment did it happen in?

* Universal Crossplane Version: 1.10.1
* Provider Version: 0.26.0

**Comment by josephferrero** [comment]
This looks to have been fixed for RDS Clusters in AWS, but not for a the single Instance type. 

https://github.com/upbound/provider-aws/pull/203

**Comment by matheusrazzup** [comment]
Is it possible to also write `port` and `username` to the secret? as @josephferrero said, on `database.aws.crossplane.io/v1beta1` all this infos are present

**Comment by josephferrero** [comment]
@matheusrazzup It looks like the port is included in the endpoint now so is not needed. I have submitted PR #475 to add the username to the secret.

**Comment by alexinthesky** [comment]
Hi I am reviving this thread as I struggle to have the [provider-sql](https://github.com/crossplane-contrib/provider-sql/) work with the connection details filled ( the provider requires the port in aa separate value see : [https://github.com/crossplane-contrib/provider-sql/blob/master/pkg/clients/postgresql/postgresql.go#L58](here) ).

unfortunatly I cannot neither do a transform in the connectionDetails. tried:
