### ISSUE TITLE
[rds]autogeneratePassword In official-provider

### ISSUE THREAD

**Issue by haooliveira84** [upbound/provider-aws#466]
### What problem are you facing?
In `crossplane-contrib/provider-aws` there is in the RDS instance a parameter called is `autogeneratePassword` this idea sounds good for replicating to the Official provider and other resources(like AmazonMQ and DocumentDB)
This feature brings us an abstraction layer in Gitops where not needed manual intervention.

**Comment by turkenf** [comment]
This was covered in PR: https://github.com/upbound/provider-aws/pull/628
