### ISSUE TITLE
Configure remaining AWS resources without testing

### ISSUE THREAD

**Issue by voloshynivan** [upbound/provider-aws#468]
### What problem are you facing?

We will have contractors coming on board to increase coverage. Currently, we configure & test the resources but configuration requires some knowledge of Upjet and Crossplane that may be hard to get them used to, i.e. we may end up spending same amount of effort reviewing their configuration vs configuring on our own.
This ticket contains remaining resources till tf provider v 4.38.0

### How could Official Providers help solve your problem?

Let's configure the remaining resources (158 CRDs) without testing and leave only the testing part to them. The exact set of API groups this issue targets will be listed below.

* `accessanalyzer`
  * [ ] [aws_accessanalyzer_archive_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/accessanalyzer_archive_rule)

* `acmpca`
  * [ ] [aws_acmpca_permission](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_permission)
  * [ ] [aws_acmpca_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_policy)

* `alb_listener`
  * [ ] [aws_alb_listener_certificate](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_certificate)
  * [ ] [aws_alb_listener_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule)

* `appconfig`
  * [ ] [aws_appconfig_extension](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appconfig_extension)
  * [ ] [aws_appconfig_extension_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appconfig_extension_association)

* `applicationinsights`
  * [ ] [aws_applicationinsights_application](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/applicationinsights_application)

* `apprunner`
  * [ ] [aws_apprunner_observability_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apprunner_observability_configuration)
  * [ ] [aws_apprunner_vpc_ingress_connection](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apprunner_vpc_ingress_connection)

* `appsync`
  * [ ] [aws_appsync_type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_type)

* `auditmanager`
  * [ ] [aws_auditmanager_account_registration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/auditmanager_account_registration)
  * [ ] [aws_auditmanager_assessment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/auditmanager_assessment)
  * [ ] [aws_auditmanager_assessment_report](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/auditmanager_assessment_report)
  * [ ] [aws_auditmanager_control](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/auditmanager_control)
  * [ ] [aws_auditmanager_framework](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/auditmanager_framework)

* `ce`
  * [ ] [aws_ce_anomaly_monitor](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_anomaly_monitor)
  * [ ] [aws_ce_anomaly_subscription](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_anomaly_subscription)
  * [ ] [aws_ce_cost_allocation_tag](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_cost_allocation_tag)

* `cloudfront`
  * [ ] [aws_cloudfront_origin_access_control](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_origin_access_control)

* `cloudwatch`
  * [ ] [aws_cloudwatch_log_data_protection_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_data_protection_policy)

* `codepipeline`
  * [ ] [aws_codepipeline_custom_action_type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codepipeline_custom_action_type)

* `cognito`
  * [ ] [aws_cognito_risk_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_risk_configuration)

* `comprehend`
  * [ ] [aws_comprehend_document_classifier](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/comprehend_document_classifier)
  * [ ] [aws_comprehend_entity_recognizer](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/comprehend_entity_recognizer)

* `connect`
  * [ ] [aws_connect_instance_storage_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_instance_storage_config)
  * [ ] [aws_connect_phone_number](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_phone_number)
  * [ ] [aws_connect_user](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_user)
  * [ ] [aws_connect_vocabulary](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_vocabulary)

* `controltower`
  * [ ] [aws_controltower_control](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/controltower_control)

* `datasync`
  * [ ] [aws_datasync_location_object_storage](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/datasync_location_object_storage)

* `directory_service`
  * [ ] [aws_directory_service_radius_settings](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_radius_settings)
  * [ ] [aws_directory_service_region](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_region)
  * [ ] [aws_directory_service_shared_directory](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_shared_directory)
  * [ ] [aws_directory_service_shared_directory_accepter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_shared_directory_accepter)

* `dms`
  * [ ] [aws_dms_s3_endpoint](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_s3_endpoint)

* `dx`
  * [ ] [aws_dx_macsec_key_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_macsec_key_association)

* `dynamodb`
  * [ ] [aws_dynamodb_table_replica](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table_replica)

* `ec2`
  * [ ] [aws_ec2_instance_state](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_instance_state)
  * [ ] [aws_ec2_network_insights_analysis](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_network_insights_analysis)
  * [ ] [aws_ec2_transit_gateway_policy_table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_policy_table)
  * [ ] [aws_ec2_transit_gateway_policy_table_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_policy_table_association)

* `efs`
  * [ ] [aws_efs_replication_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_replication_configuration)

* `emrserverless`
  * [ ] [aws_emrserverless_application](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emrserverless_application)

* `evidently`
  * [ ] [aws_evidently_feature](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_feature)
  * [ ] [aws_evidently_project](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_project)
  * [ ] [aws_evidently_segment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_segment)

* `fis`
  * [ ] [aws_fis_experiment_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fis_experiment_template)

* `fsx`
  * [ ] [aws_fsx_file_cache](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_file_cache)

* `glue`
  * [ ] [aws_glue_schema](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_schema)

* `grafana`
  * [ ] [aws_grafana_workspace_api_key](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/grafana_workspace_api_key)

* `identitystore`
  * [ ] [aws_identitystore_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_group)
  * [ ] [aws_identitystore_group_membership](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_group_membership)
  * [ ] [aws_identitystore_user](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_user)

* `inspector2`
  * [ ] [aws_inspector2_delegated_admin_account](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/inspector2_delegated_admin_account)
  * [ ] [aws_inspector2_enabler](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/inspector2_enabler)
  * [ ] [aws_inspector2_organization_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/inspector2_organization_configuration)

* `ivs`
  * [ ] [aws_ivs_channel](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ivs_channel)
  * [ ] [aws_ivs_playback_key_pair](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ivs_playback_key_pair)
  * [ ] [aws_ivs_recording_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ivs_recording_configuration)

* `ivschat`
  * [ ] [aws_ivschat_logging_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ivschat_logging_configuration)
  * [ ] [aws_ivschat_room](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ivschat_room)

* `kendra`
  * [ ] [aws_kendra_data_source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_data_source)
  * [ ] [aws_kendra_experience](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_experience)
  * [ ] [aws_kendra_faq](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_faq)
  * [ ] [aws_kendra_index](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_index)
  * [ ] [aws_kendra_query_suggestions_block_list](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_query_suggestions_block_list)
  * [ ] [aws_kendra_thesaurus](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_thesaurus)

* `kms`
  * [ ] [aws_kms_custom_key_store](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_custom_key_store)

* `lakeformation`
  * [ ] [aws_lakeformation_lf_tag](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lakeformation_lf_tag)
  * [ ] [aws_lakeformation_resource_lf_tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lakeformation_resource_lf_tags)

* `lightsail`
  * [ ] [aws_lightsail_bucket](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_bucket)
  * [ ] [aws_lightsail_certificate](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_certificate)
  * [ ] [aws_lightsail_container_service](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_container_service)
  * [ ] [aws_lightsail_container_service_deployment_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_container_service_deployment_version)
  * [ ] [aws_lightsail_database](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_database)
  * [ ] [aws_lightsail_disk](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_disk)
  * [ ] [aws_lightsail_disk_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_disk_attachment)
  * [ ] [aws_lightsail_domain_entry](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_domain_entry)
  * [ ] [aws_lightsail_lb](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_lb)
  * [ ] [aws_lightsail_lb_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_lb_attachment)
  * [ ] [aws_lightsail_lb_certificate](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_lb_certificate)
  * [ ] [aws_lightsail_lb_certificate_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_lb_certificate_attachment)
  * [ ] [aws_lightsail_lb_https_redirection_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_lb_https_redirection_policy)
  * [ ] [aws_lightsail_lb_stickiness_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lightsail_lb_stickiness_policy)

* `location`
  * [ ] [aws_location_geofence_collection](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_geofence_collection)
  * [ ] [aws_location_place_index](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_place_index)
  * [ ] [aws_location_route_calculator](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_route_calculator)
  * [ ] [aws_location_tracker](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_tracker)
  * [ ] [aws_location_tracker_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/location_tracker_association)

* `macie2`
  * [ ] [aws_macie2_classification_export_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_classification_export_configuration)

* `medialive`
  * [ ] [aws_medialive_channel](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_channel)
  * [ ] [aws_medialive_input](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_input)
  * [ ] [aws_medialive_input_security_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_input_security_group)
  * [ ] [aws_medialive_multiplex](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_multiplex)
  * [ ] [aws_medialive_multiplex_program](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_multiplex_program)

* `msk`
  * [ ] [aws_msk_serverless_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_serverless_cluster)

* `neptune`
  * [ ] [aws_neptune_global_cluster](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/neptune_global_cluster)

* `networkfirewall`
  * [ ] [aws_networkfirewall_firewall](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkfirewall_firewall)

* `networkmanager`
  * [ ] [aws_networkmanager_attachment_accepter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_attachment_accepter)
  * [ ] [aws_networkmanager_connect_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_connect_attachment)
  * [ ] [aws_networkmanager_core_network](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_core_network)
  * [ ] [aws_networkmanager_site_to_site_vpn_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_site_to_site_vpn_attachment)
  * [ ] [aws_networkmanager_transit_gateway_peering](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_transit_gateway_peering)
  * [ ] [aws_networkmanager_transit_gateway_route_table_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_transit_gateway_route_table_attachment)
  * [ ] [aws_networkmanager_vpc_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_vpc_attachment)

* `opensearch`
  * [ ] [aws_opensearch_inbound_connection_accepter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_inbound_connection_accepter)
  * [ ] [aws_opensearch_outbound_connection](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_outbound_connection)

* `rds`
  * [ ] [aws_rds_export_task](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_export_task)
  * [ ] [aws_rds_reserved_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_reserved_instance)

* `redshift`
  * [ ] [aws_redshift_authentication_profile](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_authentication_profile)
  * [ ] [aws_redshift_cluster_iam_roles](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_cluster_iam_roles)
  * [ ] [aws_redshift_endpoint_access](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_endpoint_access)
  * [ ] [aws_redshift_endpoint_authorization](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_endpoint_authorization)
  * [ ] [aws_redshift_hsm_client_certificate](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_hsm_client_certificate)
  * [ ] [aws_redshift_hsm_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_hsm_configuration)
  * [ ] [aws_redshift_partner](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_partner)
  * [ ] [aws_redshift_usage_limit](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_usage_limit)
  * [ ] [aws_redshiftdata_statement](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshiftdata_statement)
  * [ ] [aws_redshiftserverless_endpoint_access](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshiftserverless_endpoint_access)
  * [ ] [aws_redshiftserverless_namespace](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshiftserverless_namespace)
  * [ ] [aws_redshiftserverless_resource_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshiftserverless_resource_policy)
  * [ ] [aws_redshiftserverless_snapshot](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshiftserverless_snapshot)
  * [ ] [aws_redshiftserverless_usage_limit](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshiftserverless_usage_limit)
  * [ ] [aws_redshiftserverless_workgroup](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshiftserverless_workgroup)

* `resourceexplorer2`
  * [ ] [aws_resourceexplorer2_index](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/resourceexplorer2_index)
  * [ ] [aws_resourceexplorer2_view](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/resourceexplorer2_view)

* `rolesanywhere`
  * [ ] [aws_rolesanywhere_profile](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rolesanywhere_profile)
  * [ ] [aws_rolesanywhere_trust_anchor](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rolesanywhere_trust_anchor)

* `route53`
  * [ ] [aws_route53_resolver_config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_resolver_config)

* `rum`
  * [ ] [aws_rum_app_monitor](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rum_app_monitor)
  * [ ] [aws_rum_metrics_destination](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rum_metrics_destination)

* `s3`
  * [ ] [aws_s3control_storage_lens_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_storage_lens_configuration)

* `sagemaker`
  * [ ] [aws_sagemaker_servicecatalog_portfolio_status](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_servicecatalog_portfolio_status)
  * [ ] [aws_sagemaker_space](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_space)

* `scheduler`
  * [ ] [aws_scheduler_schedule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/scheduler_schedule)
  * [ ] [aws_scheduler_schedule_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/scheduler_schedule_group)

* `schemas`
  * [ ] [aws_schemas_registry_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/schemas_registry_policy)

* `sesv2`
  * [ ] [aws_sesv2_configuration_set](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_configuration_set)
  * [ ] [aws_sesv2_configuration_set_event_destination](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_configuration_set_event_destination)
  * [ ] [aws_sesv2_dedicated_ip_assignment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_dedicated_ip_assignment)
  * [ ] [aws_sesv2_dedicated_ip_pool](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_dedicated_ip_pool)
  * [ ] [aws_sesv2_email_identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_email_identity)
  * [ ] [aws_sesv2_email_identity_feedback_attributes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_email_identity_feedback_attributes)
  * [ ] [aws_sesv2_email_identity_mail_from_attributes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sesv2_email_identity_mail_from_attributes)

* `sqs`
  * [ ] [aws_sqs_queue_redrive_allow_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue_redrive_allow_policy)
  * [ ] [aws_sqs_queue_redrive_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue_redrive_policy)

* `ssm`
  * [ ] [aws_ssm_default_patch_baseline](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_default_patch_baseline)
  * [ ] [aws_ssm_service_setting](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_service_setting)

* `ssoadmin`
  * [ ] [aws_ssoadmin_customer_managed_policy_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_customer_managed_policy_attachment)
  * [ ] [aws_ssoadmin_instance_access_control_attributes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_instance_access_control_attributes)
  * [ ] [aws_ssoadmin_permissions_boundary_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_permissions_boundary_attachment)

* `transcribe`
  * [ ] [aws_transcribe_language_model](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transcribe_language_model)
  * [ ] [aws_transcribe_medical_vocabulary](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transcribe_medical_vocabulary)
  * [ ] [aws_transcribe_vocabulary](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transcribe_vocabulary)
  * [ ] [aws_transcribe_vocabulary_filter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transcribe_vocabulary_filter)

* `transfer`
  * [ ] [aws_transfer_tag](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_tag)

* `vpc_network`
  * [ ] [aws_vpc_network_performance_metric_subscription](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_network_performance_metric_subscription)

**Comment by voloshynivan** [comment]
Configurations will be done in scope of tickets: #470, #471, #472, #473, #474

**Comment by sergenyalcin** [comment]
It seems that, the related tickets were done. Closing.
