### ISSUE TITLE
Configure sns (3)

### ISSUE THREAD

**Issue by luebken** [upbound/provider-aws#47]
External name configuration of 3 resources in the `sns` group:
* [`aws_sns_platform_application`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_platform_application)
* [`aws_sns_sms_preferences`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_sms_preferences)
* [`aws_sns_topic_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic_policy)

Extracted from https://github.com/upbound/provider-aws/issues/55

**Comment by ulucinar** [comment]
Corresponding issue: https://github.com/upbound/provider-aws/issues/254
