### ISSUE TITLE
Moving rds (4) resources to v1beta1 version

### ISSUE THREAD

**Issue by ezgidemirel** [upbound/provider-aws#48]
Moving 4 resources in the `rds` group:

- [x] [aws_db_cluster_snapshot](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_cluster_snapshot)
- [x] [aws_db_event_subscription](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_event_subscription)
- [x] [aws_db_instance_automated_backups_replication](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance_automated_backups_replication)
- [x] [aws_db_snapshot_copy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_snapshot_copy)

**Comment by svscheg** [comment]
While configuration "aws_db_snapshot_copy": config.IdentifierFromProvider, - it started and created successfully, but SYNCED will be marked as False with next error:

- lastTransitionTime: "2022-12-24T14:46:05Z"
    message: 'observe failed: cannot run plan: plan failed: Instance cannot be destroyed:
      Resource aws_db_snapshot_copy.example has lifecycle.prevent_destroy set, but
      the plan calls for this resource to be destroyed. To avoid this error and continue
      with the plan, either disable lifecycle.prevent_destroy or reduce the scope
      of the plan using the -target flag.'
    reason: ReconcileError

Tryed change configuration config.NameAsIdentifier,config.ParameterAsIdentifier("target_db_snapshot_identifier") "aws_db_snapshot_copy": FormattedIdentifierFromProvider(",", "source_db_snapshot_identifier", "target_db_snapshot_identifier") but it give the same error or didn't work.
