### ISSUE TITLE
Configure vpc (5)

### ISSUE THREAD

**Issue by muvaf** [upbound/provider-aws#53]
External name configuration of 5 resources in the `vpc` group:
* [`aws_vpc_endpoint_connection_accepter`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint_connection_accepter)
* [`aws_vpc_endpoint_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint_policy)
* [`aws_vpc_endpoint_security_group_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint_security_group_association)
* [`aws_vpc_ipam_organization_admin_account`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_organization_admin_account)
* [`aws_vpc_ipam_preview_next_cidr`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_ipam_preview_next_cidr)

s

**Comment by sergenyalcin** [comment]
These resources were configured
