### ISSUE TITLE
Configure securityhub (11),serverlessrepo (1),servicecatalog (13),servicediscovery (2)

### ISSUE THREAD

**Issue by muvaf** [upbound/provider-aws#56]
External name configuration of 11 resources in the `securityhub` group:
* [`aws_securityhub_account`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_account)
* [`aws_securityhub_action_target`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_action_target)
* [`aws_securityhub_finding_aggregator`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_finding_aggregator)
* [`aws_securityhub_insight`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_insight)
* [`aws_securityhub_invite_accepter`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_invite_accepter)
* [`aws_securityhub_member`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_member)
* [`aws_securityhub_organization_admin_account`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_organization_admin_account)
* [`aws_securityhub_organization_configuration`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_organization_configuration)
* [`aws_securityhub_product_subscription`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_product_subscription)
* [`aws_securityhub_standards_control`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_standards_control)
* [`aws_securityhub_standards_subscription`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_standards_subscription)

External name configuration of 1 resources in the `serverlessrepo` group:
* [`aws_serverlessapplicationrepository_cloudformation_stack`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/serverlessapplicationrepository_cloudformation_stack)

External name configuration of 13 resources in the `servicecatalog` group:
* [`aws_servicecatalog_budget_resource_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_budget_resource_association)
* [`aws_servicecatalog_constraint`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_constraint)
* [`aws_servicecatalog_organizations_access`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_organizations_access)
* [`aws_servicecatalog_portfolio`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_portfolio)
* [`aws_servicecatalog_portfolio_share`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_portfolio_share)
* [`aws_servicecatalog_principal_portfolio_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_principal_portfolio_association)
* [`aws_servicecatalog_product`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_product)
* [`aws_servicecatalog_product_portfolio_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_product_portfolio_association)
* [`aws_servicecatalog_provisioned_product`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_provisioned_product)
* [`aws_servicecatalog_provisioning_artifact`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_provisioning_artifact)
* [`aws_servicecatalog_service_action`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_service_action)
* [`aws_servicecatalog_tag_option`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_tag_option)
* [`aws_servicecatalog_tag_option_resource_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicecatalog_tag_option_resource_association)

External name configuration of 2 resources in the `servicediscovery` group:
* [`aws_service_discovery_http_namespace`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/service_discovery_http_namespace)
* [`aws_service_discovery_instance`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/service_discovery_instance)

**Comment by ulucinar** [comment]
Because https://github.com/upbound/official-providers/issues/381 has been closed as completed, removing `secretsmanager` resources from this issue.

**Comment by ulucinar** [comment]
This issue has been split into the following issues after untested configurations have been implemented in the provider:
- https://github.com/upbound/provider-aws/issues/188
- https://github.com/upbound/provider-aws/issues/189
- https://github.com/upbound/provider-aws/issues/190
- https://github.com/upbound/provider-aws/issues/191
