### ISSUE TITLE
Configure s3control (3),s3outposts (1),sagemaker (23),schemas (3)

### ISSUE THREAD

**Issue by muvaf** [upbound/provider-aws#57]
External name configuration of 3 resources in the `s3control` group:
* [`aws_s3control_multi_region_access_point_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_multi_region_access_point_policy)
* [`aws_s3control_object_lambda_access_point`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_object_lambda_access_point)
* [`aws_s3control_object_lambda_access_point_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3control_object_lambda_access_point_policy)

External name configuration of 1 resources in the `s3outposts` group:
* [`aws_s3outposts_endpoint`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3outposts_endpoint)

External name configuration of 23 resources in the `sagemaker` group:
* [`aws_sagemaker_app`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_app)
* [`aws_sagemaker_app_image_config`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_app_image_config)
* [`aws_sagemaker_code_repository`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_code_repository)
* [`aws_sagemaker_device`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_device)
* [`aws_sagemaker_device_fleet`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_device_fleet)
* [`aws_sagemaker_domain`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_domain)
* [`aws_sagemaker_endpoint`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_endpoint)
* [`aws_sagemaker_endpoint_configuration`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_endpoint_configuration)
* [`aws_sagemaker_feature_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_feature_group)
* [`aws_sagemaker_flow_definition`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_flow_definition)
* [`aws_sagemaker_human_task_ui`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_human_task_ui)
* [`aws_sagemaker_image`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_image)
* [`aws_sagemaker_image_version`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_image_version)
* [`aws_sagemaker_model`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_model)
* [`aws_sagemaker_model_package_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_model_package_group)
* [`aws_sagemaker_model_package_group_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_model_package_group_policy)
* [`aws_sagemaker_notebook_instance`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_notebook_instance)
* [`aws_sagemaker_notebook_instance_lifecycle_configuration`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_notebook_instance_lifecycle_configuration)
* [`aws_sagemaker_project`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_project)
* [`aws_sagemaker_studio_lifecycle_config`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_studio_lifecycle_config)
* [`aws_sagemaker_user_profile`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_user_profile)
* [`aws_sagemaker_workforce`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_workforce)
* [`aws_sagemaker_workteam`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_workteam)

External name configuration of 3 resources in the `schemas` group:
* [`aws_schemas_discoverer`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/schemas_discoverer)
* [`aws_schemas_registry`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/schemas_registry)
* [`aws_schemas_schema`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/schemas_schema)

**Comment by sergenyalcin** [comment]
Some API groups were configured without testing and some of them were moved to v1beta1.
