### ISSUE TITLE
rds: `DBCluster` writeConnectionSecret missing fields

### ISSUE THREAD

**Issue by blakebarnett** [upbound/provider-aws#574]
Similar to the issue reported and fixed here: https://github.com/upbound/provider-aws/issues/442

The RDS Cluster resource does not write the username or port field to the connection secret by default and is no configurable via `publishConnectionDetails`.

### What happened?
Connection secret gets written with only these fields:
`attribute.master_password`
`endpoint`
`reader_endpoint`

### How can we reproduce it?
Create an RDS cluster resource (and cluster instances) and check the connection secret.

### What environment did it happen in?

* Universal Crossplane Version: v1.11.0
* Provider Version: v0.29
* Cloud provider or hardware configuration: AWS m6i.xlarge nodes
* Kubernetes version (use `kubectl version`): `v1.24.8-eks-ffeb93d`
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): `EKS`
* OS (e.g. from /etc/os-release): Amazon Linux 2
* Kernel (e.g. `uname -a`): N/A

**Comment by haarchri** [comment]
good starting point is the following commit for aws_db_instance: https://github.com/upbound/provider-aws/commit/a36dba4765886009d7ca259529af1be76645540e to add a contribution ;)

**Comment by svscheg** [comment]
Fix: https://github.com/upbound/provider-aws/pull/703
