### ISSUE TITLE
Configure opsworks (2),organizations (6),pinpoint (11),qldb (2),quicksight (4),rds (1)

### ISSUE THREAD

**Issue by muvaf** [upbound/provider-aws#58]
External name configuration of 2 resources in the `opsworks` group:
* [`aws_opsworks_static_web_layer`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_static_web_layer)
* [`aws_opsworks_user_profile`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opsworks_user_profile)

External name configuration of 6 resources in the `organizations` group:
* [`aws_organizations_account`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/organizations_account)
* [`aws_organizations_delegated_administrator`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/organizations_delegated_administrator)
* [`aws_organizations_organization`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/organizations_organization)
* [`aws_organizations_organizational_unit`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/organizations_organizational_unit)
* [`aws_organizations_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/organizations_policy)
* [`aws_organizations_policy_attachment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/organizations_policy_attachment)

External name configuration of 11 resources in the `pinpoint` group:
* [`aws_pinpoint_adm_channel`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_adm_channel)
* [`aws_pinpoint_apns_channel`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_apns_channel)
* [`aws_pinpoint_apns_sandbox_channel`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_apns_sandbox_channel)
* [`aws_pinpoint_apns_voip_channel`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_apns_voip_channel)
* [`aws_pinpoint_apns_voip_sandbox_channel`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_apns_voip_sandbox_channel)
* [`aws_pinpoint_app`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_app)
* [`aws_pinpoint_baidu_channel`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_baidu_channel)
* [`aws_pinpoint_email_channel`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_email_channel)
* [`aws_pinpoint_event_stream`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_event_stream)
* [`aws_pinpoint_gcm_channel`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_gcm_channel)
* [`aws_pinpoint_sms_channel`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_sms_channel)

External name configuration of 2 resources in the `qldb` group:
* [`aws_qldb_ledger`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/qldb_ledger)
* [`aws_qldb_stream`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/qldb_stream)

External name configuration of 4 resources in the `quicksight` group:
* [`aws_quicksight_data_source`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_data_source)
* [`aws_quicksight_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_group)
* [`aws_quicksight_group_membership`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_group_membership)
* [`aws_quicksight_user`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_user)

External name configuration of 1 resources in the `rds` group:
* [`aws_db_cluster_snapshot`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_cluster_snapshot)

**Comment by sergenyalcin** [comment]
Some API groups were configured without testing and some of them were moved to v1beta1.
