### ISSUE TITLE
buckets: kubectl get buckets executes lightsail API

### ISSUE THREAD

**Issue by slonokot** [upbound/provider-aws#590]
### What happened?
 kubectl get buckets isseus lightail requests instead of s3 as result not returning created buckets:

```shell
...
# kubectl api-resources  | grep buckets
buckets                                                  lightsail.aws.upbound.io/v1beta1                      false        Bucket
buckets                                                  s3.aws.upbound.io/v1beta1                             false        Bucket
...

# kubectl get buckets
No resources found
# kubectl get  buckets.s3.aws.upbound.io
NAME                      READY   SYNCED   EXTERNAL-NAME             AGE
crossplane-bucket-5mzz8   True    False    crossplane-bucket-5mzz8   34m
```
When installing provider  version v0.30.0 and trying

### How can we reproduce it?

Go through [official docs](https://docs.crossplane.io/v1.11/getting-started/provider-aws/) and try creating s3 bucket from the example list it. 

### What environment did it happen in?

* Universal Crossplane Version: v1.11
* Provider Version:  v0.30.0

**Comment by jeanduplessis** [comment]
@slonokot in provider-aws v0.30 we added support for [Lightsail](https://aws.amazon.com/lightsail/), which introduced [bucket.lightsail.aws.upbound.io](http://bucket.lightsail.aws.upbound.io/). As a result, the full name is required for S3 buckets.

For example: `kube get bucket.s3.aws.upbound.io`

**Comment by slonokot** [comment]
@jeanduplessis thank you for  the quick response!
I understand the behavior. There are other CRDs that has this, for example `queues` (you'd expect it to return SQS queues) but there's another CRD taking precedence. This behavior doesn't seem to be the same as for `crossplane-contrib` aws provider. As such when AWS decides to provide new service and the new API will mask an old one this may introduce breaking changes.

Is it possible to modify the CRD  generation in a way that there will be no such masking happening? A couple of suggestions:
