### ISSUE TITLE
aws_eks_addon: wrong external name 

### ISSUE THREAD

**Issue by duizabojul** [upbound/provider-aws#603]
### What happened?

The external name of aws_eks_addon is not built correctly: 

Actually it is `"aws_eks_addon": FormattedIdentifierUserDefinedNameLast("addon_name", ":", "cluster_name")`, it should be `"aws_eks_addon": FormattedIdentifierFromProvider(":", "cluster_name", "addon_name")`

We have tested it, it works like a charm.  

### What environment did it happen in?

* Universal Crossplane Version: 1.11.1
* Provider Version: 0.30.0

**Comment by svscheg** [comment]
Hi @duizabojul ! Could you please fix PR https://github.com/upbound/provider-aws/pull/604 adding  addonName: vpc-cni to the examples/eks/addon.yaml? Seems after changes you miss add it for the examples/eks/addon.yaml so we have failed test check in PR.

**Comment by duizabojul** [comment]
@svscheg done

**Comment by svscheg** [comment]
@duizabojul could you please fix examples/eks/addon.yaml once again with attached [addon.yaml](https://github.com/upbound/provider-aws/files/11104308/addon.yaml.txt) from my comment? seems it should fix problem with running uptest. 
Thank you.

**Comment by duizabojul** [comment]
@svscheg done

**Comment by svscheg** [comment]
I am sorry, I attached wrong yaml file.
@duizabojul could you please use this one to fix test (it contains all necessary dependency): 
[addon.yaml.txt](https://github.com/upbound/provider-aws/files/11105851/addon.yaml.txt)

**Comment by duizabojul** [comment]
@svscheg done
