### ISSUE TITLE
Add prefixListId ref and selector for aws_route and aws_security_group_rule

### ISSUE THREAD

**Issue by duizabojul** [upbound/provider-aws#605]
### What problem are you facing?

We need to resolve `aws_ec2_managed_prefix_list` reference in `aws_route` and `aws_security_group_rule` resources using ref and selector.

**Comment by svscheg** [comment]
**For the aws_route:** we have parameterdestinationPrefixListId, need add destinationPrefixListIdRef and destinationPrefixListIdSelector

**For the aws_security_group_rule:** we have prefixListIds, need add prefixListIdRefs and prefixListIdSelector
