### ISSUE TITLE
Configure fms (2),fsx (10),glacier (2)

### ISSUE THREAD

**Issue by muvaf** [upbound/provider-aws#62]
External name configuration of 2 resources in the `fms` group:
* [`aws_fms_admin_account`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fms_admin_account)
* [`aws_fms_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fms_policy)

External name configuration of 10 resources in the `fsx` group:
* [`aws_fsx_backup`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_backup)
* [`aws_fsx_data_repository_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_data_repository_association)
* [`aws_fsx_lustre_file_system`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_lustre_file_system)
* [`aws_fsx_ontap_file_system`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_file_system)
* [`aws_fsx_ontap_storage_virtual_machine`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_storage_virtual_machine)
* [`aws_fsx_ontap_volume`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_volume)
* [`aws_fsx_openzfs_file_system`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_openzfs_file_system)
* [`aws_fsx_openzfs_snapshot`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_openzfs_snapshot)
* [`aws_fsx_openzfs_volume`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_openzfs_volume)
* [`aws_fsx_windows_file_system`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_windows_file_system)

External name configuration of 2 resources in the `glacier` group:
* [`aws_glacier_vault`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glacier_vault)
* [`aws_glacier_vault_lock`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glacier_vault_lock)

**Comment by sergenyalcin** [comment]
These API groups were configured without testing
