### ISSUE TITLE
Configure elastictranscoder (1),elbv2 (4),emr (7),emrcontainers (1),events (8)

### ISSUE THREAD

**Issue by muvaf** [upbound/provider-aws#63]
External name configuration of 1 resources in the `elastictranscoder` group:
* [`aws_elastictranscoder_preset`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elastictranscoder_preset)

External name configuration of 4 resources in the `elbv2` group:
* [`aws_alb_listener_certificate`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/alb_listener_certificate)
* [`aws_alb_listener_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/alb_listener_rule)
* [`aws_lb_listener_certificate`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_certificate)
* [`aws_lb_listener_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule)

External name configuration of 7 resources in the `emr` group:
* [`aws_emr_cluster`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_cluster)
* [`aws_emr_instance_fleet`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_instance_fleet)
* [`aws_emr_instance_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_instance_group)
* [`aws_emr_managed_scaling_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_managed_scaling_policy)
* [`aws_emr_security_configuration`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_security_configuration)
* [`aws_emr_studio`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_studio)
* [`aws_emr_studio_session_mapping`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_studio_session_mapping)

External name configuration of 1 resources in the `emrcontainers` group:
* [`aws_emrcontainers_virtual_cluster`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emrcontainers_virtual_cluster)

External name configuration of 8 resources in the `events` group:
* [`aws_cloudwatch_event_api_destination`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_api_destination)
* [`aws_cloudwatch_event_archive`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_archive)
* [`aws_cloudwatch_event_bus`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_bus)
* [`aws_cloudwatch_event_bus_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_bus_policy)
* [`aws_cloudwatch_event_connection`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_connection)
* [`aws_cloudwatch_event_permission`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_permission)
* [`aws_cloudwatch_event_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_rule)
* [`aws_cloudwatch_event_target`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target)

**Comment by sergenyalcin** [comment]
These API groups were configured without testing.
