### ISSUE TITLE
Moving elasticsearch (2) resources to v1beta1 version

### ISSUE THREAD

**Issue by muvaf** [upbound/provider-aws#64]
External name configuration of 3 resources in the `elasticsearch` group:
* [`aws_elasticsearch_domain_policy`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain_policy)
* [`aws_elasticsearch_domain_saml_options`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain_saml_options)

**Comment by kdibrov** [comment]
- aws_elasticsearch_domain_policy is not being generated after configuration 
- aws_elasticsearch_domain_saml_options requires a physical file attachment (xml file)
