### ISSUE TITLE
ResourceAssociation for resource sharing only allows subnets

### ISSUE THREAD

**Issue by SeanLeFevreCricut** [upbound/provider-aws#662]
### What happened?
When attempting to add a transit gateway using to a ResourceAssociation the following error occurs:

cannot resolve references: mg.Spec.ForProvider.ResourceArn: cannot get referenced resource: Subnet.ec2.aws.upbound.io "[transitgateway-name]" not found

### How can we reproduce it?
1. Create a TransitGateway
2. Create a ResourceShare
3. Create a ResourceAssociation using resourceArnRef: with the name of the TransitGateway

apiVersion: ram.aws.upbound.io/v1beta1
kind: ResourceAssociation
metadata:
  name: name-ra
spec:
  forProvider:
    region: [region]
    resourceArnRef:
      name: [transitgateway-name]
    resourceShareArnRef:
      name: [resourceshare-name]
  providerConfigRef:
    name: [provider-config]

### What environment did it happen in?

* Crossplane Version:
* Provider Version: v0.32.1
* Kubernetes Version: 1.25
* Kubernetes Distribution: EKS

**Comment by haarchri** [comment]
https://github.com/crossplane/crossplane-runtime/issues/350
