### ISSUE TITLE
Instructions on building a cut-down version of the provider-aws provider

### ISSUE THREAD

**Issue by felipe88alves** [upbound/provider-aws#674]
Just wondering if there are any clear/easy instructions on building a forked provider-aws provider with less support than the main package.

I'm thinking of something similar to the following instructions to filter out unneeded configs for azure provider: 

> - Commented out unneeded resources: https://github.com/grafana/crossplane-provider-azure/blob/main/config/externalname.go#L15
> - Commented out unneeded configs: https://github.com/grafana/crossplane-provider-azure/blob/main/config/provider.go#L115
> - make generate
> - Changed the publish account to our Upbound org: https://github.com/grafana/crossplane-provider-azure/blob/main/Makefile#L71
> - Push, and a version is created in our private provider
> - On a new release, we can cherry-pick our commit onto it

**Comment by portswigger-tim** [comment]
@felipe88alves - in case you haven't seen, Upbound providers have been split out into service-specific provider families in `v0.36.0` - https://blog.upbound.io/new-provider-families 

If that looks like what you were after, you could close this issue :)

**Comment by felipe88alves** [comment]
Still doesn't answer my question, but I'll close the issue anyway given it's been a while with no answers.

Even with the new provider families I'll still only be using 6% of the CRDs I'd need to install, so my need is still very much there.

**Comment by elohmrow** [comment]
@felipe88alves this might be interesting to you: https://github.com/crossplane/crossplane/issues/4192

**Comment by portswigger-tim** [comment]
I asked a similar question in Slack and found out about the provider family split, which was a step in the right direction. Maybe allowing users to pass in a list of resources as a command line arg through ControllerConfig would be an interesting idea.
