### ISSUE TITLE
Moving codecommit (3),codedeploy (3),codepipeline (2),codestarconnections (2),codestarnotifications (1) resources to v1beta1 version

### ISSUE THREAD

**Issue by muvaf** [upbound/provider-aws#68]
Moving 3 resources in the `codecommit` group:
- [x] [`aws_codecommit_approval_rule_template_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codecommit_approval_rule_template_association)
- [x] [`aws_codecommit_repository`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codecommit_repository)
- [x] [`aws_codecommit_trigger`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codecommit_trigger)
- [x] [`aws_codecommit_approval_rule_template`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codecommit_approval_rule_template)

Moving 3 resources in the `codedeploy` group:
- [x] [`aws_codedeploy_app`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codedeploy_app)
- [x] [`aws_codedeploy_deployment_config`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codedeploy_deployment_config)
- [x] [`aws_codedeploy_deployment_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codedeploy_deployment_group)

Moving 2 resources in the `codepipeline` group:
- [x] [`aws_codepipeline`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codepipeline)
- [x] [`aws_codepipeline_webhook`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codepipeline_webhook)

Moving 2 resources in the `codestarconnections` group:
- [x] [`aws_codestarconnections_connection`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codestarconnections_connection)
- [x] [`aws_codestarconnections_host`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codestarconnections_host)

Moving 1 resources in the `codestarnotifications` group:
- [x] [`aws_codestarnotifications_notification_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codestarnotifications_notification_rule)

**Comment by turkenh** [comment]
PR by @turkenf, configuring `codecommit` group: https://github.com/upbound/provider-aws/pull/91

**Comment by turkenh** [comment]
`codedeploy` and `codepipeline: `https://github.com/upbound/provider-aws/pull/102
