### ISSUE TITLE
Request for `aws_vpc_security_group_egress_rule` and `aws_vpc_security_group_ingress_rule` resource

### ISSUE THREAD

**Issue by huynhsontung** [upbound/provider-aws#683]
### What resource do you need?

Terraform Resource Names: 
- `aws_vpc_security_group_egress_rule`
- `aws_vpc_security_group_ingress_rule`

### What is your use case?

These two resources are the replacements for `aws_security_group_rule`. I have encountered situations where Terraform (and by extension AWS Provider) cannot reconcile changes with `aws_security_group_rule` resources. There is also a warning front and center on [the resource docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule) about potential issues with the old security group rule.

**Comment by turkenf** [comment]
PR opened by @huynhsontung: https://github.com/upbound/provider-aws/pull/685
