### ISSUE TITLE
Cannot deploy RDS instance that references RDS security group

### ISSUE THREAD

**Issue by junglie85** [upbound/provider-aws#691]
### What happened?

Cannot create a RDS instance that references RDS security groups.

```
    Message:               apply failed: with the retirement of EC2-Classic no new RDS DB Instances can be created referencing RDS DB Security Groups:
```

### How can we reproduce it?

Deploy an RDS instance that references a RDS security group.

### What environment did it happen in?

* Crossplane Version: 1.12.1
* Provider Version: 0.34.0
* Kubernetes Version:  
* Kubernetes Distribution:

**Comment by haarchri** [comment]
please create securityGroup from EC2 Group and use it with https://marketplace.upbound.io/providers/upbound/provider-aws/v0.34.0/resources/rds.aws.upbound.io/Instance/v1beta1#doc:spec-forProvider-vpcSecurityGroupIdRefs

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_security_group
`With the retirement of EC2-Classic the aws_db_security_group resource has been deprecated and will be removed in a future version.`

**Comment by haarchri** [comment]
@sergenyalcin  think we can should remove security group in rds group

**Comment by turkenf** [comment]
Thanks for raising this issue @junglie85, Please see this [comment](https://github.com/upbound/provider-aws/issues/689#issuecomment-1536194049)

Thanks for the quick response @haarchri, I agree with you.

**Comment by junglie85** [comment]
Yes, the EC2 security groups work for me - I only just got around to updating these issues from yesterday. It would be helpful to remove the deprecated API elements and update the docs/examples accordingly.
