### ISSUE TITLE
Moving appsync (8) resources to v1beta1 version

### ISSUE THREAD

**Issue by muvaf** [upbound/provider-aws#70]
Moving 8 resources in the `appsync` group:
-  [ ] [`aws_appsync_api_cache`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_api_cache)
-  [ ] [`aws_appsync_api_key`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_api_key)
-  [ ] [`aws_appsync_datasource`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_datasource)
-  [ ] [`aws_appsync_domain_name`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_domain_name)
-  [ ] [`aws_appsync_domain_name_api_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_domain_name_api_association)
-  [ ] [`aws_appsync_function`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_function)
-  [ ] [`aws_appsync_graphql_api`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_graphql_api)
-  [ ] [`aws_appsync_resolver`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_resolver)

**Comment by turkenf** [comment]
autoscaling, autoscalingplans resources were extracted to https://github.com/upbound/provider-aws/issues/174
