### ISSUE TITLE
AWS Provider and Minio

### ISSUE THREAD

**Issue by yaroslavkasatikov** [upbound/provider-aws#705]
Hi team,

I tried to use the provider while creating s3 bucket into Minio

I have changed providerconfig:

```spec:
  credentials:
    secretRef:
      key: creds
      name: aws-secret
      namespace: crossplane-system
    source: Secret
  endpoint:
    hostnameImmutable: true
    url:
      static: http://10.0.64.3:32502
      type: Static
```

and created bucket. Physically the bucket has been created, but in resource status I see this output (check the screenshot). So, if you remove/change CR, it is not affected on created bucket. Also the error in status doesn't allow to use it in depended resources.

<img width="1340" alt="image" src="https://github.com/crossplane-contrib/provider-aws/assets/7746585/5cb9967e-16ed-4717-b14c-23939abb4e0d">

I tried on different version of provider. for example it is applied on   xpkg.upbound.io/crossplane-contrib/provider-aws:v0.39.0

**Comment by svscheg** [comment]
Hi @yaroslavkasatikov ! Thank you for raising this issue.
Could you please add more information like MR example to reproduce this issue?

**Comment by turkenf** [comment]
Since there has been no response to this issue for a long time, I am closing it for now. If you still need more help with this issue, feel free to reopen or add a comment.

**Comment by whummer** [comment]
@yaroslavkasatikov Maybe you can give it a try with [LocalStack](https://github.com/localstack/localstack) - we've recently had great experiences using the Crossplane AWS provider against LocalStack, and also added some docs here: https://docs.localstack.cloud/user-guide/integrations/crossplane/ Please keep us posted on how it goes.. Thanks!
