### ISSUE TITLE
Significant memory usage with golangci-lint

### ISSUE THREAD

**Issue by stevendborrelli** [upbound/provider-aws#737]
### What happened?

When running `make reviewable test`, golangci-lint v1.50.0 will use significant amounts of memory, often being killed by the OS.

Below are screenshots from testing on Mac M1 and Linux systems showing memory usage in the 40+GB: 

![image](https://github.com/upbound/provider-aws/assets/414702/8995f255-82b7-413d-b662-22651e7651ca)

![image](https://github.com/upbound/provider-aws/assets/414702/1cd3c414-3d33-4447-8598-07a323891068)

There are numerous issues on the golangci-lint repo: https://github.com/golangci/golangci-lint/issues/3536 

### How can we reproduce it?

Run `make reviewable test`, observe memory usage of the golangci-ling process.

### What environment did it happen in?

* Crossplane Version:
* Provider Version: master branch
* Kubernetes Version:  1.27.1
* Kubernetes Distribution: kind

**Comment by stevendborrelli** [comment]
@phisco has a workaround for now:

```console
GO_LINT_ARGS=" --disable musttag " make -e reviewable test
```

**Comment by turkenf** [comment]
@stevendborrelli, the upstream issue had closed and the related PR had merged, is this issue still valid?

**Comment by turkenf** [comment]
Thanks for the information @phisco.

**Comment by turkenf** [comment]
Covered with https://github.com/upbound/provider-aws/pull/829
