### ISSUE TITLE
Incorrect ID for policies with paths

### ISSUE THREAD

**Issue by portswigger-tim** [upbound/provider-aws#742]
### What happened?
After restarting the AWS provider, `policy` objects with a path become not `Ready`. I believe it is because the initial tfstate id and the composed tfstate id are different. The composed state after a restart does not contain the path in the ARN used in the id field. This results in an error:

```
apply failed: creating IAM Policy (crossplane-app-policy-pg-license-only-test):
      EntityAlreadyExists: A policy called crossplane-app-policy-pg-license-only-test
      already exists. Duplicate names are not allowed.\n\tstatus code: 409, request
      id: uuid-of-error-event
```

### How can we reproduce it?
Create an IAM policy object with a path and restart the IAM provider. 

### What environment did it happen in?

* Crossplane Version: v1.12.2
* Provider Version: v0.36.0
* Kubernetes Version: 1.26
* Kubernetes Distribution: EKS

**Comment by portswigger-tim** [comment]
I can confirm that the id contains the path after creating a new policy, but the generated id does not contain the path.

**Comment by julienduchesne** [comment]
We have encounter the same issue. 

To note that the policies initially look good (if they are created by crossplane) but at some point they become unready and will not get back to normal due to a policy conflict (trying to recreate the same policy)

it also makes it impossible to “import” policies with a path

**Comment by svscheg** [comment]
The issue is relevant for the latest master
