### ISSUE TITLE
AWS autoscale doesn't work properly when desiredSize is set in the nodegroup resource

### ISSUE THREAD

**Issue by abhinavbalasundaram** [upbound/provider-aws#756]
We have been using crossplanecontrib/provider-aws v38.0 for creating a nodegroup on AWS. And we are now trying to move to upbound/provider-aws v37.0, but we run into a problem related to auto scaling. In the crossplanecontrib when we created nodegroup managedresource we did not set anything for the desiredSize in the scalingConfig. So the AWS was able to autoscale based on the workload. But in the upbound provider, the desiredSize is now a mandatory field, so we set it to 1. Although AWS tries to autoscale, crossplane reconciles to the desiredSize that we provided, which is causing the nodes to constantly get terminated and recreated.

* Crossplane Version: 1.12.2
* Provider Version: v37
* Kubernetes Version: 1.24
* Kubernetes Distribution: EKS

          scalingConfig:
          - minSize: 1
            maxSize: 10
            desiredSize: 1

https://doc.crds.dev/github.com/crossplane/provider-aws/eks.aws.crossplane.io/NodeGroup/v1alpha1@v0.41.0#spec-forProvider-scalingConfig-desiredSize

https://marketplace.upbound.io/providers/upbound/provider-aws-eks/v0.37.0/resources/eks.aws.upbound.io/NodeGroup/v1beta1#doc:spec-forProvider-scalingConfig-desiredSize

**Comment by bobh66** [comment]
I think this can be fixed by adding:
```
               r.LateInitializer = config.LateInitializer{
                        IgnoredFields: []string{
                                "desired_size",
                        },
                }
```

to the EKS Nodegroup in eks/config.go

I'll test the patch and push it if it works.

**Comment by lsviben** [comment]
Hey, this is one of the use cases of the [Granular management policies feature](https://github.com/crossplane/crossplane/blob/master/design/one-pager-ignore-changes.md#eks-nodegroup), which we are currently working on.

So it should be fixed by it when it goes live. One note is that it is currently an alpha feature but we will be working on promoting it to beta in the next releases.

**Comment by jeanduplessis** [comment]
With granular management policies reaching beta in version 0.43.0 the correct way to address it would be to use that feature. Closing this issue for now.
