### ISSUE TITLE
Error configuring serverlessV2 scaling configuration for RDS Aurora

### ISSUE THREAD

**Issue by seanlucey** [upbound/provider-aws#827]
### What happened?
Trying to create an RDS Aurora Cluster with Serverless v2. When applying max and min capacity, i receive the error:
`
* spec.forProvider.serverlessv2ScalingConfiguration[0].maxCapacity: Required value
* spec.forProvider.serverlessv2ScalingConfiguration[1].minCapacity: Required value
`
### How can we reproduce it?
Achieved inserting the following ClusterSet:
```
    serverlessv2ScalingConfiguration:
      - minCapacity: 1
      - maxCapacity: 2
```

### What environment did it happen in?

* Crossplane Version: 1.12.2
* Provider Version: 0.38.0
* Kubernetes Version: 1.27.3
* Kubernetes Distribution: EKS

**Comment by mbbush** [comment]
```
serverlessv2ScalingConfiguration:
      - minCapacity: 1
      - maxCapacity: 2
```
Should be
```
serverlessv2ScalingConfiguration:
      - minCapacity: 1
        maxCapacity: 2
```

**Comment by cloudymax** [comment]
> ```
> serverlessv2ScalingConfiguration:
>       - minCapacity: 1
>       - maxCapacity: 2
> ```
> 
> Should be
> 
> ```
> serverlessv2ScalingConfiguration:
>       - minCapacity: 1
>         maxCapacity: 2
> ```

😲

That did the trick!
