### ISSUE TITLE
AWS Account ID Variable doesn't resolve

### ISSUE THREAD

**Issue by ppapp92** [upbound/provider-aws#846]
### What happened?

Variable `${data.aws_caller_identity.current.account_id}` returns error in KMS Key example.

### How can we reproduce it?

Try example https://github.com/upbound/provider-aws/blob/main/examples/route53/hostedzonednssec.yaml for the KMS Key.

Crossplane returns:

```
observe failed: cannot run refresh: refresh failed: Reference to
undeclared resource: A data resource "aws_caller_identity" "current" has
not been declared in the root module.
``` 

### What environment did it happen in?

* Crossplane Version: v1.12.3-up.1 
* Provider Version: v0.38.0 
* Kubernetes Version: v1.25.12-eks-2d98532
* Kubernetes Distribution: EKS

**Comment by haarchri** [comment]
We use uptest to test all our examples, which involves injecting dynamic values. You can find more information about injecting dynamic values and using a datasource here: https://github.com/upbound/uptest#injecting-dynamic-values-and-datasource

In your case make sure to include your AWS Account ID when using this example

**Comment by ppapp92** [comment]
Hi @haarchri,

Thank you for the explanation that clears it up perfectly!
