### ISSUE TITLE
AccountAssignment.ssoadmin.aws.upbound.io/v1beta1 is missing permissionSetArnRef.

### ISSUE THREAD

**Issue by kevans-theorem** [upbound/provider-aws#888]
### What problem are you facing?

We're using `ssoadmin.aws.upbound.io/v1beta1` for our AWS multi-account IAM set up and while most of the CRDs support `permissionSetArnRef`, the `AccountAssignment` spec is missing it, which requires either hardcoding the ARN in or a patch.  It'd be great if we just had parity across all those CRDs so it could be fully dynamic and reusable.

### How could Official AWS Provider help solve your problem?

https://github.com/upbound/provider-aws/blob/main/package/crds/ssoadmin.aws.upbound.io_permissionsetinlinepolicies.yaml#L83 is an example of the field I'm referring to.

https://github.com/upbound/provider-aws/blob/main/package/crds/ssoadmin.aws.upbound.io_accountassignments.yaml#L328 is where it's omitted.

**Comment by mbbush** [comment]
I'm currently working on setting up my SSO integration using crossplane, and can probably take a look at this and other improvements as well.

**Comment by mbbush** [comment]
@kevans-theorem Thanks for the issue report! 

Just FYI in case you're inclined to contribute other similar references, both of the places you linked are in generated code, so the actual change happens elsewhere. You can look at the changes my PR makes to config.go, but it's really just a handful of lines of code and then running `make generate`. I put codegen and manual edits in different commits in my PR to make it easier to follow.

I still want to make other SSO improvements (like adding identitystore users and groups, and references to them), but this is so small that I'm doing it in a separate PR to keep it simple.

**Comment by kevans-theorem** [comment]
> @kevans-theorem Thanks for the issue report!
> 
> Just FYI in case you're inclined to contribute other similar references, both of the places you linked are in generated code, so the actual change happens elsewhere. You can look at the changes my PR makes to config.go, but it's really just a handful of lines of code and then running `make generate`. I put codegen and manual edits in different commits in my PR to make it easier to follow.
> 
> I still want to make other SSO improvements (like adding identitystore users and groups, and references to them), but this is so small that I'm doing it in a separate PR to keep it simple.

Thanks for jumping on this!  I had considered trying it myself but as you see, I'm not super familiar with this style of generated code and the workflow around it.  I'll definitely refer to this PR if I run into another spot where I could contribute a similar style of change.
