### ISSUE TITLE
Error Invalid parameter: SubscriptionArn when I try to create subscription topic

### ISSUE THREAD

**Issue by sterziev88** [upbound/provider-aws#935]
What happened?
When I try to add SNS topic subscription to my lambda I receive an error.

How can we reproduce it?
---
apiVersion: sns.aws.upbound.io/v1beta1
kind: Topic
metadata:
  name: example-sns-topic
spec:
  forProvider:
    region: us-east-1
---
apiVersion: sns.aws.upbound.io/v1beta1
kind: TopicSubscription
metadata:
  name: example-sns-topic-test
spec:
  forProvider:
    endpoint: "arn:aws:lambda:eu-west-1:xxxx:function:test-lambda"
    protocol: lambda
    region: eu-west-1
    topicArnRef:
      name: example-sns-topic

Apply the above and you will get the following error:
observe failed: cannot run refresh: refresh failed: reading SNS Topic Subscription (siem-data): InvalidParameter: Invalid parameter: SubscriptionArn Reason: An ARN must have at least 6 elements, not 1\n\tstatus code: 400, request id: fb315d6c-e3a6-5bba-b85e-00df1484d5c3: "

What environment did it happen in?
Provider Version: provider-aws 0.38

**Comment by mbbush** [comment]
Can you please post the output of `kubectl get topicsubscription example-sns-topic-test -o yaml`.

**Comment by sterziev88** [comment]
Hi Matthew,  that is that output from the yaml:

`apiVersion: sns.aws.upbound.io/v1beta1
kind: TopicSubscription
metadata:
  creationTimestamp: "2023-10-26T05:10:24Z"
  generation: 2
  labels:
    sns-topic-name: siem-data
  name: siem-data-subscription
  resourceVersion: "1308086"
  uid: 885765f4-e7e6-4fed-a902-cf8f1a8ba672
spec:
  deletionPolicy: Delete
  forProvider:
    endpoint: arn:aws:lambda:eu-west-1:xxxxx:function:test-lambda
    protocol: lambda
    region: eu-west-1
    topicArn: arn:aws:sns:eu-west-1:xxxxx:siem-data
    topicArnRef:
      name: siem-data
    topicArnSelector:
      matchLabels:
        createdByCrossplane: "true"
        envName: mgmt
        envType: green
        sns-topic-name: siem-data
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: aws-provider-upbound-mgmt
status:
  atProvider: {}
  conditions:
  - lastTransitionTime: "2023-10-26T05:28:48Z"
    message: "observe failed: cannot run refresh: refresh failed: reading SNS Topic
      Subscription (siem-data): InvalidParameter: Invalid parameter: SubscriptionArn
      Reason: An ARN must have at least 6 elements, not 1\n\tstatus code: 400, request
      id: 96f8f170-716b-555e-9d8e-acc38a3b558c: "
    reason: ReconcileError
    status: "False"
    type: Synced`

**Comment by sterziev88** [comment]
It was temporary issue, now it is ok.
