### ISSUE TITLE
Backport #933 to v0.40, v0.41 and v0.42

### ISSUE THREAD

**Issue by jeanduplessis** [upbound/provider-aws#944]
### What problem are you facing?

The release notes for the affected versions have been updated with the following notice:

> [!IMPORTANT]  
> Provider version 0.40 introduced a regression (see #929) related to IAM roles and role policy attachments. The issue was fixed in provider version 0.43.0. If you haven't installed versions 0.40.0, 0.41.0 or 0.42.0 into your cluster, we recommend skipping those releases and upgrading directly to 0.43.0 when you choose to upgrade. If you have installed one of the affected releases, we recommend upgrading to an unaffected release (0.43+), and then you will need to unset the `spec.forProvider.managedPolicyArns` value from any `Role.iam.aws.upbound.io` managed resources that you want to be able to use `RolePolicyAttachment` resources to attach policies to.

We should backport #933 to these versions so that users can use the patch release rather than having to skip multiple versions.

**Comment by haarchri** [comment]
its also needed to cleanup the roles with a script like:

`kubectl get [role.iam.aws.upbound.io](http://role.iam.aws.upbound.io/) -o name | xargs kubectl patch --dry-run=server --patch '[{"op":"remove","path":"/spec/forProvider/managedPolicyArns"}]' --type=json`
