### ISSUE TITLE
Request for `aws_eks_pod_identity_association` resource

### ISSUE THREAD

**Issue by danielloader** [upbound/provider-aws#985]
### What resource do you need?

Terraform Resource Name: aws_eks_pod_identity_association

### What is your use case?

It's significantly less painful than using IRSA with EKS and it's currently brewing over at the [terraform provider](https://github.com/hashicorp/terraform-provider-aws/pull/34566). 

https://aws.amazon.com/blogs/aws/amazon-eks-pod-identity-simplifies-iam-permissions-for-applications-on-amazon-eks-clusters/

Putting this issue up to get ahead of that and track the issue.

**Comment by Smana** [comment]
Hello, just wondering how can we help get this added to this provider. Actually, I don't know what the process anyway to follow the Terraform's recent changes. Could you please guide us?

**Comment by quanlk2511** [comment]
Hello, is there anyone working on this?

**Comment by mbbush** [comment]
> Hello, is there anyone working on this?

Yes. 

There are a couple open PRs where I see the core maintainers testing various examples with the new terraform provider version. 

Terraform provider AWS version 5.x contains breaking changes, and many resources have been migrated from the terraform plugin SDK to the terraform plugin framework, which is not yet supported by the new no-fork upjet architecture that brought huge performance improvements. That's being worked on, too. 

If you want to be more up to date with what's happening with this project, check out the crossplane community meeting every 2 weeks. The notes are public, past meetings are on YouTube, and anyone can join the zoom. More details are on crossplane slack.

**Comment by quanlk2511** [comment]
Thanks a lot @mbbush , I'll follow-up with  meetings. Cheers!
