### ISSUE TITLE
cannot configure no-fork client because the length of assume role chain array is more than 1

### ISSUE THREAD

**Issue by rbrunan** [upbound/provider-aws#998]
### What happened?

After upgrading the aws provider in a dev environment to test `v0.44.0` we saw a problem with the reconciliation of the MRs deployed:
```
Warning  CannotConnectToProvider  38s (x6 over 101s)      managed/iam.aws.upbound.io/v1beta1, kind=role  cannot initialize the no-fork async external client: cannot get terraform setup: could not configure no-fork AWS client: cannot configure no-fork client because the length of assume role chain array is more than 1
```
A similar behavior was described in https://github.com/upbound/provider-aws/issues/971 and was expected to be resolved in `v0.45.0`. 

However, we see this (other?) issue after upgrading to `v0.45.0`. All the MRs from different split aws providers fail with:
```
    Last Transition Time:  2023-12-01T13:39:31Z
    Message:               connect failed: cannot initialize the no-fork async external client: cannot get terraform setup: could not configure no-fork AWS client: cannot configure no-fork client because the length of assume role chain array is more than 1
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
```

### How can we reproduce it?

```
❯ kc get providers
NAME                          INSTALLED   HEALTHY   PACKAGE                                                                 AGE
provider-argocd               True        True      xpkg.upbound.io/crossplane-contrib/provider-argocd:v0.1.0-26.ga23f109   65d
provider-aws-autoscaling      True        True      xpkg.upbound.io/upbound/provider-aws-autoscaling:v0.45.0                18d
provider-aws-ec2              True        True      xpkg.upbound.io/upbound/provider-aws-ec2:v0.45.0                        65d
provider-aws-eks              True        True      xpkg.upbound.io/upbound/provider-aws-eks:v0.45.0                        65d
provider-aws-iam              True        True      xpkg.upbound.io/upbound/provider-aws-iam:v0.45.0                        65d
provider-aws-kafka            True        True      xpkg.upbound.io/upbound/provider-aws-kafka:v0.45.0                      22d
provider-kubernetes           True        True      xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.9.0           65d
upbound-provider-family-aws   True        True      xpkg.upbound.io/upbound/provider-family-aws:v0.45.0                     6m53s
```
Provider config:
```
API Version:  aws.upbound.io/v1beta1
Kind:         ProviderConfig
...
Spec:
  Assume Role Chain:
    Role ARN:  arn:aws:iam::<ACCOUNT1>:role/service-role/crossplane1
    Role ARN:  arn:aws:iam::<ACCOUNT2>:role/service-role/crossplane2
  Credentials:
    Source:  IRSA
```
### What environment did it happen in?

* Crossplane Version: `v1.13.2`
* Provider Version: `v0.45.0`
* Kubernetes Version: `v1.26.10-eks-4f4795d`  
* Kubernetes Distribution: EKS

**Comment by haarchri** [comment]
https://github.com/upbound/provider-aws/pull/989/files#diff-308cecf2f1479ee3978d7847071c7876558f33745e5fe49e57174f5a53961055R259
think this is still valid when i check the code; 

> // Terraform AWS provider does not support role chaining via provider configuration
> // https://github.com/hashicorp/terraform-provider-aws/issues/22728

**Comment by rbrunan** [comment]
> https://github.com/upbound/provider-aws/pull/989/files#diff-308cecf2f1479ee3978d7847071c7876558f33745e5fe49e57174f5a53961055R259 think this is still valid when i check the code;
> 
> > // Terraform AWS provider does not support role chaining via provider configuration
> > // [hashicorp/terraform-provider-aws#22728](https://github.com/hashicorp/terraform-provider-aws/issues/22728)

Thanks for the response @haarchri. We can deploy resources with Crossplane with the `v0.43.1` version with the same provider configuration. Is this a new limitation?

**Comment by jeanduplessis** [comment]
The team has identified the issue and will be submitting a PR to fix this soon. We'll follow it up with a patch release for the provider.

**Comment by erhancagirici** [comment]
@rbrunan thanks for reporting this. This limitation was known but eliminated now, a change is underway. Would you be interested in testing from your side too, in a dev environment if we provide a test image including the fix? Thanks!

**Comment by rbrunan** [comment]
Ok, thanks all. 
I can help with the testing but I'll be available for that after December 11th.

**Comment by go-faustino** [comment]
Hi @erhancagirici! I'm hitting the same issue, I could help test these changes on my dev environment.

**Comment by erhancagirici** [comment]
@go-faustino thanks! could you try an example AWS IAM resource with the following images? 
`index.docker.io/erhancag/provider-family-aws:v0.45.0-fix998`
`index.docker.io/erhancag/provider-aws-iam:v0.45.0-fix998`

**Comment by rbrunan** [comment]
Thank you folks. I've tested the `v0.45.0` and it's solving this issue as expected.
